services:
  booklet:
    image: booklet
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    env_file:
      .env
    ports:
      - "5432:5432"
    volumes:
      - booklet-db:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    env_file:
      .env
    ports:
      - "5050:80"

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
    booklet-db:
