spring:
  cache:
    type: redis
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      cache-null-values: false
      time-to-live: 60000

  application:
    name: booklet

  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true  # to disable warning

  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

server:
  error:
    include-stacktrace: on_param

management:
  endpoints:
    web:
      exposure:
        include: "*"
