spring:
  main:
    allow-bean-definition-overriding: true
  data:
    rest:
      base-path: /api/v1
      detection-strategy: annotated

  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false
      key-prefix: "booklet:"

  application:
    name: booklet

  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true  # to disable warning

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  config:
    activate:
      on-profile: debug, dev, local, test

server:
  error:
    include-stacktrace: always
