spring:
  application:
    name: booklet

  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/booklet
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true  # to disable warning

  security:
    jwt:
      secret-key: bxBWG9rIQcquX1UubhgI5lIqF4B6+N0GBBN5v/eCSss=

server:
  error:
    include-stacktrace: on_param

management:
  endpoints:
    web:
      exposure:
        include: "*"
