apiVersion: apps/v1
kind: Deployment
metadata:
  name: booklet
  namespace: booklet
  labels:
    app: booklet
spec:
  replicas: 4
  selector:
    matchLabels:
      app: booklet
  template:
    metadata:
      labels:
        app: booklet
    spec:
      containers:
        - name: booklet
          image: togrulir/booklet:latest
          imagePullPolicy: Never
          ports:
            - protocol: TCP
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: booklet-configmap
            - secretRef:
                name: booklet-secret
