apiVersion: v1
kind: Service
metadata:
  name: booklet-service
spec:
  selector:
    app: booklet
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30162
