apiVersion: v1
kind: ConfigMap
metadata:
  name: booklet-config
  namespace: booklet
data:
  POSTGRES_DB: "booklet"
  POSTGRES_HOST: "postgresl"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  JDBC_URL: "jdbc:postgresql://postgres:5432/booklet"
