create table author
(
    rating     numeric(2, 1)
        constraint rating_validness_check check (rating >= 0 AND rating <= 5),
    birth_date timestamp(6) not null,
    death_date timestamp(6),
    name       varchar(50)  not null,
    surname    varchar(50)  not null,
    biography  TEXT         not null,
    id         varchar(255) generated by default as identity,
    primary key (id)
);
create table genre
(
    id   bigint generated by default as identity,
    name varchar(50) not null,
    slug varchar(50) not null,
    primary key (id)
);
create table book
(
    year      integer      not null,
    genre_id  bigint,
    id        bigint generated by default as identity,
    isbn      varchar(13) unique,
    title     varchar(100) not null,
    author_id varchar(255),
    primary key (id),
    foreign key (author_id) references author,
    foreign key (genre_id) references genre

);