CREATE TABLE author
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(50)                             NOT NULL,
    surname    VARCHAR(50)                             NOT NULL,
    birth_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    death_date TIMESTAMP WITHOUT TIME ZONE,
    biography  TEXT                                    NOT NULL,
    rating     DECIMAL(2, 1),
    CONSTRAINT pk_author PRIMARY KEY (id)
);

CREATE TABLE book
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title     VARCHAR(100)                            NOT NULL,
    author_id BIGINT,
    genre_id  BIGINT,
    isbn      VARCHAR(13),
    year      INTEGER                                 NOT NULL,
    CONSTRAINT pk_book PRIMARY KEY (id)
);

CREATE TABLE genre
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    slug VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_genre PRIMARY KEY (id)
);

ALTER TABLE book
    ADD CONSTRAINT uc_book_isbn UNIQUE (isbn);

ALTER TABLE book
    ADD CONSTRAINT FK_BOOK_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES author (id);

ALTER TABLE book
    ADD CONSTRAINT FK_BOOK_ON_GENRE FOREIGN KEY (genre_id) REFERENCES genre (id);