CREATE TABLE token
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token   VARCHAR(255) UNIQUE                     NOT NULL,
    active  BOOLEAN                                 NOT NULL,
    user_id BIGINT,
    CONSTRAINT pk_token PRIMARY KEY (id),
    CONSTRAINT FK_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES accounts (id)
);

ALTER TABLE accounts
    ADD email VARCHAR(255) UNIQUE;

ALTER TABLE accounts
    ALTER COLUMN email SET NOT NULL;

ALTER TABLE accounts
    DROP COLUMN username;
